# Generated by Django 2.0.1 on 2019-03-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fname', models.CharField(max_length=200)),
                ('workArea', models.CharField(max_length=200)),
                ('skill', models.CharField(max_length=200)),
            ],
        ),
    ]
