# Generated by Django 2.0.1 on 2019-03-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0006_auto_20190319_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, help_text='50x50px', upload_to='worker/photo'),
        ),
    ]
