# Generated by Django 2.0.1 on 2019-03-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0007_auto_20190319_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
