# Generated by Django 2.0.1 on 2019-03-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0008_listservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listservice',
            old_name='name',
            new_name='namecategory',
        ),
    ]
