# Generated by Django 2.0.1 on 2019-03-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0010_auto_20190320_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('body', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='workArea',
        ),
        migrations.DeleteModel(
            name='ListService',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
